spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
  application: 
    name: storecloud-config-store-dev
---
spring:
  profiles: test   #测试环境
  application: 
    name: storecloud-config-store-test
#  请保存为UTF-8格式
 
 
